### ISSUE TITLE
On run docker i have error: Error: listen EAFNOSUPPORT: address family not supported :::8080 .

### ISSUE THREAD

**Issue by andrejs82git** [hectorm/demergi#467]
Hi!
when i try run docker.

` docker run --network my_ipv4_network -p 8080:8080 ghcr.io/hectorm/demergi:latest`
 
 I get that error:
 ```
node:net:1881
      const error = new UVExceptionWithHostPort(rval, 'listen', address, port);
                    ^

Error: listen EAFNOSUPPORT: address family not supported :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1881:21)
    at listenInCluster (node:net:1946:12)
    at doListen (node:net:2116:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EAFNOSUPPORT',
  errno: -97,
  syscall: 'listen',
  address: '::',
  port: 8080
}

Node.js v20.13.1
```

**Comment by andrejs82git** [comment]
docker run -p 8080:8080 ghcr.io/hectorm/demergi:latest -A 0.0.0.0:8080


Like that it working. Thanks a lot !!!!!

**Comment by hectorm** [comment]
By default it tries to listen on `[::]:8080`, so if IPv6 is not enabled it will fail (maybe it should do a fallback to IPv4, I will look into it at some point), the solution for now is the one you found.
